services:
  postgres-reading-tracker-db:
    image: postgres:16
    container_name: postgres-reading-tracker
    environment:
      POSTGRES_DB: reading_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5441:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reading_tracker"]
      interval: 5s
      timeout: 5s
      retries: 10
